# Generated by Django 5.2.17 on 2026-09-29 00:25

import core.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='título')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='texto de apoio')),
                ('eyebrow', models.CharField(default='CAMAROTE RESENHA MORUMBI', max_length=80, verbose_name='chamada')),
                ('image', models.ImageField(upload_to=core.models.upload_path, verbose_name='imagem do banner')),
                ('button_text', models.CharField(default='Ver eventos', max_length=60, verbose_name='texto do botão')),
                ('link', models.CharField(default='/#eventos', max_length=500, verbose_name='link do botão')),
                ('active', models.BooleanField(default=True, verbose_name='exibir na página inicial')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('texts', models.JSONField(blank=True, default=dict)),
                ('instagram', models.URLField(default='https://www.instagram.com/resenhamorumbi/')),
                ('whatsapp', models.CharField(blank=True, max_length=15)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, upload_to=core.models.upload_path)),
                ('hero_image', models.ImageField(blank=True, upload_to=core.models.upload_path)),
                ('football_image', models.ImageField(blank=True, upload_to=core.models.upload_path)),
                ('concert_image', models.ImageField(blank=True, upload_to=core.models.upload_path)),
                ('experience_image', models.ImageField(blank=True, upload_to=core.models.upload_path)),
                ('pix_key', models.CharField(blank=True, max_length=77)),
                ('pix_name', models.CharField(blank=True, max_length=25)),
                ('pix_city', models.CharField(default='SAO PAULO', max_length=15)),
                ('sales_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuração do site',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=180)),
                ('object_id', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160, verbose_name='nome do evento')),
                ('description', models.TextField(max_length=10000, verbose_name='descrição')),
                ('category', models.CharField(choices=[('football', 'Futebol'), ('concert', 'Show')], max_length=16, verbose_name='categoria')),
                ('starts_at', models.DateTimeField(verbose_name='data e horário')),
                ('doors_at', models.TimeField(blank=True, null=True, verbose_name='abertura do camarote')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='preço por ingresso')),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)], verbose_name='quantidade de ingressos')),
                ('max_per_order', models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='limite por pedido')),
                ('location', models.CharField(default='MorumBIS • São Paulo, SP', max_length=240, verbose_name='local')),
                ('includes', models.TextField(blank=True, max_length=2000, verbose_name='o que está incluído (um item por linha)')),
                ('age_rules', models.CharField(blank=True, max_length=600, verbose_name='classificação etária e regras')),
                ('cover', models.ImageField(blank=True, upload_to=core.models.upload_path, verbose_name='foto de capa')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('closed', 'Encerrado')], default='draft', max_length=16, verbose_name='situação')),
                ('featured', models.BooleanField(default=False, verbose_name='evento em destaque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['status', 'starts_at'], name='core_event_status_d39a79_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='event_capacity_positive'), models.CheckConstraint(condition=models.Q(('price__gte', 1)), name='event_price_positive')],
            },
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.upload_path)),
                ('caption', models.CharField(blank=True, max_length=240)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.event')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=180, verbose_name='descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor')),
                ('kind', models.CharField(choices=[('expense', 'Despesa'), ('withdrawal', 'Retirada')], default='expense', max_length=16, verbose_name='tipo')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.CharField(default=core.models.order_token, editable=False, max_length=64, unique=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Aguardando pagamento'), ('review', 'Em análise'), ('paid', 'Confirmado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('receipt', models.ImageField(blank=True, storage=core.models.private_storage, upload_to=core.models.private_image_path)),
                ('official_ticket', models.FileField(blank=True, storage=core.models.private_storage, upload_to=core.models.ticket_path)),
                ('request_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('pix_snapshot', models.JSONField(default=dict)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.event')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'status', 'expires_at'], name='core_order_event_i_b49d76_idx'), models.Index(fields=['ip_hash', 'created_at'], name='core_order_ip_hash_96f5f1_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='order_quantity_positive')],
            },
        ),
    ]
