# Generated by Django 5.2

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_source',
            field=models.CharField(
                choices=[
                    ('ticketmaster', 'Ticketmaster'),
                    ('spfc', 'São Paulo FC'),
                    ('producer', 'Produtor / organizador'),
                    ('other', 'Outro'),
                ],
                default='ticketmaster',
                max_length=20,
                verbose_name='origem do ingresso',
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_source_notes',
            field=models.CharField(
                blank=True,
                help_text='Opcional. Ex.: lote do camarote, produtor responsável ou observação interna.',
                max_length=240,
                verbose_name='detalhes da origem',
            ),
        ),
        migrations.CreateModel(
            name='OrderTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=core.models.private_storage, upload_to=core.models.ticket_path, verbose_name='ingresso oficial')),
                ('label', models.CharField(blank=True, max_length=80, verbose_name='identificação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
