# All customer-facing editorial copy and purchase labels can be edited in the panel.
CONTENT = {
'Identidade e navegação': {
'brand_name':'Resenha','brand_place':'MORUMBI','nav_events':'Eventos','nav_experience':'O camarote','nav_faq':'Dúvidas','nav_contact':'Contato','nav_cta':'Escolha sua resenha',
},
'Banner principal':{
'hero_eyebrow':'CAMAROTE RESENHA MORUMBI','hero_title':'O jogo é no campo.\nA resenha é aqui.','hero_description':'A emoção do São Paulo. A energia dos grandes shows. Viva o MorumBIS com uma experiência que vai muito além do ingresso.','hero_button':'Explore os eventos','hero_secondary':'Conheça o camarote','hero_caption':'MORUMBIS, SÃO PAULO','hero_tag':'FUTEBOL • MÚSICA • BOAS HISTÓRIAS',
},
'Eventos':{
'events_eyebrow':'ESCOLHA SEU PRÓXIMO ENCONTRO','events_title':'Toda grande história\ncomeça com um ingresso.','events_description':'No gramado ou no palco, seu lugar na resenha está aqui.','filter_all':'Todos os eventos','filter_football':'Jogos do São Paulo','filter_concert':'Shows','empty_title':'A próxima resenha está chegando.','empty_description':'Estamos preparando a agenda de jogos e shows. Acompanhe o Instagram e fique por dentro da abertura das vendas.','empty_button':'Acompanhe no Instagram','football_title':'O Tricolor, de perto.','football_text':'Cada lance. Cada grito. Cada encontro. Viva um dia de São Paulo com a sua turma.','concert_title':'No volume da sua emoção.','concert_text':'Grandes artistas e noites que viram história. O show começa com uma boa resenha.','category_soon':'NOVA PROGRAMAÇÃO EM BREVE','event_cta':'Ver evento','sold_out':'Ingressos esgotados','from_price':'Por pessoa','event_about':'Sobre o evento','event_includes':'Sua experiência inclui','event_rules':'Antes de comprar','event_date':'Data e horário','event_location':'Local','event_doors':'Abertura do camarote','buy_button':'Garantir meus ingressos','sales_paused':'Vendas ainda não abertas para este evento.',
},
'O camarote':{
'experience_eyebrow':'MAIS QUE UM CAMAROTE','experience_title':'A melhor parte\né viver junto.','experience_text':'Reúna os amigos, sinta a energia do MorumBIS e deixe o resto com a resenha. Um espaço para transformar jogos e shows em boas memórias.','experience_note':'Confira os serviços incluídos e as condições na página de cada evento.','benefit_1_title':'Emoção de perto','benefit_1_text':'O MorumBIS como cenário para momentos que ficam.','benefit_2_title':'Boa companhia','benefit_2_text':'Um ponto de encontro para quem vive o futebol e a música.','benefit_3_title':'Uma experiência completa','benefit_3_text':'Conheça as opções de serviços disponíveis em cada evento.',
},
'Dúvidas frequentes':{
'faq_eyebrow':'ANTES DA RESENHA','faq_title':'Pode chegar. A gente explica.','faq_1_q':'Como funciona a compra?','faq_1_a':'Escolha um evento, informe seus dados e a quantidade de ingressos. Faça o Pix e envie o comprovante na página do pedido. Nossa equipe confere o recebimento antes de confirmar sua compra.','faq_2_q':'O que está incluído no ingresso?','faq_2_a':'Os serviços variam de acordo com o evento. Confira os itens incluídos, horários e regras na página do jogo ou show antes de comprar.','faq_3_q':'Como recebo meu ingresso?','faq_3_a':'Após a confirmação do pagamento, acompanhe a página do seu pedido. O ingresso oficial será disponibilizado pela equipe. O comprovante de compra não substitui o ingresso de acesso ao estádio.','faq_4_q':'Posso ir com crianças ou adolescentes?','faq_4_a':'A classificação etária e a necessidade de acompanhamento variam por evento. Consulte as regras do evento escolhido e fale com a equipe antes da compra.',
},
'Contato e rodapé':{
'contact_title':'A resenha continua\nno Instagram.','contact_text':'Bastidores, próximos eventos e tudo o que acontece por aqui.','contact_button':'@resenhamorumbi','footer_text':'Futebol, música e histórias para contar.','footer_location':'MorumBIS • São Paulo, SP','footer_copyright':'Camarote Resenha Morumbi. Todos os direitos reservados.','footer_admin':'Área administrativa','footer_terms':'Informações da compra','terms_title':'Informações da compra','terms_text':'Leia a descrição, data, classificação etária, serviços incluídos e condições do evento antes de concluir o pedido. O pagamento via Pix passa por conferência manual. A confirmação e o ingresso oficial ficam disponíveis na página privada do pedido. Para dúvidas, cancelamentos ou solicitação de reembolso, entre em contato com a equipe pelo canal divulgado no site. Os dados informados no pedido são utilizados para processar a compra e prestar atendimento. Guarde o link do seu pedido em segurança.',
},
'Compra e pedidos':{
'checkout_title':'Seu lugar na resenha.','checkout_description':'Preencha seus dados para reservar os ingressos e pagar com Pix.','name_label':'Nome completo','email_label':'E-mail','phone_label':'Celular com DDD','quantity_label':'Quantidade de ingressos','terms_label':'Li as informações da compra e as regras deste evento.','checkout_submit':'Reservar e pagar com Pix','checkout_notice':'A reserva dura 30 minutos. O pagamento será confirmado após a conferência da equipe.','order_title':'Acompanhe seu pedido','order_total':'Total do pedido','order_pending':'Faça o Pix e envie seu comprovante antes de a reserva expirar.','order_review':'Comprovante recebido. Nossa equipe vai conferir o pagamento.','order_paid':'Pagamento confirmado. Seu ingresso oficial aparecerá aqui assim que a equipe disponibilizá-lo.','order_cancelled':'Este pedido foi cancelado. Se você já pagou, entre em contato com a equipe.','order_refunded':'O reembolso deste pedido foi registrado pela equipe.','order_expired':'A reserva expirou. Não efetue o pagamento. Caso já tenha pago, entre em contato com a equipe.','pix_copy':'Copiar Pix Copia e Cola','receipt_label':'Comprovante (JPG, PNG ou WebP, até 8 MB)','receipt_button':'Enviar comprovante','order_ticket':'Baixar ingresso oficial','order_link_notice':'Guarde esta página. O link dá acesso ao seu pedido e deve ser mantido em segurança.','order_voucher_notice':'Esta página é um comprovante de compra e não permite acesso ao estádio. Utilize o ingresso oficial disponibilizado pela equipe.',
}}
DEFAULT_TEXTS={key:value for group in CONTENT.values() for key,value in group.items()}
LABELS={key:key.replace('_',' ').capitalize() for key in DEFAULT_TEXTS}

FIELD_LABELS = {
'brand_name':'Nome da marca','brand_place':'Complemento da marca','nav_events':'Menu: Eventos','nav_experience':'Menu: O camarote','nav_faq':'Menu: Dúvidas','nav_contact':'Menu: Contato','nav_cta':'Botão do cabeçalho',
'hero_eyebrow':'Chamada do banner','hero_title':'Título do banner','hero_description':'Descrição do banner','hero_button':'Botão principal','hero_secondary':'Link secundário','hero_caption':'Local na base do banner','hero_tag':'Faixa abaixo do banner',
'events_eyebrow':'Chamada da seção','events_title':'Título da seção','events_description':'Descrição da seção','filter_all':'Filtro: Todos','filter_football':'Filtro: Futebol','filter_concert':'Filtro: Shows','empty_title':'Título sem eventos','empty_description':'Texto sem eventos','empty_button':'Botão sem eventos','football_title':'Título do cartão de futebol','football_text':'Descrição do cartão de futebol','concert_title':'Título do cartão de shows','concert_text':'Descrição do cartão de shows','category_soon':'Aviso de programação em breve','event_cta':'Botão do cartão do evento','sold_out':'Mensagem de ingressos esgotados','from_price':'Rótulo do preço','event_about':'Título: Sobre o evento','event_includes':'Título: Itens incluídos','event_rules':'Título: Regras','event_date':'Rótulo da data','event_location':'Rótulo do local','event_doors':'Rótulo da abertura','buy_button':'Botão de compra','sales_paused':'Mensagem de vendas pausadas',
'experience_eyebrow':'Chamada da seção','experience_title':'Título da seção','experience_text':'Descrição do camarote','experience_note':'Observação sobre serviços','benefit_1_title':'Benefício 1: título','benefit_1_text':'Benefício 1: descrição','benefit_2_title':'Benefício 2: título','benefit_2_text':'Benefício 2: descrição','benefit_3_title':'Benefício 3: título','benefit_3_text':'Benefício 3: descrição',
'faq_eyebrow':'Chamada da seção','faq_title':'Título da seção','faq_1_q':'Pergunta 1','faq_1_a':'Resposta 1','faq_2_q':'Pergunta 2','faq_2_a':'Resposta 2','faq_3_q':'Pergunta 3','faq_3_a':'Resposta 3','faq_4_q':'Pergunta 4','faq_4_a':'Resposta 4',
'contact_title':'Título do contato','contact_text':'Descrição do contato','contact_button':'Botão do Instagram','footer_text':'Texto abaixo da marca','footer_location':'Local no rodapé','footer_copyright':'Direitos autorais','footer_admin':'Link administrativo','footer_terms':'Link de informações da compra','terms_title':'Título das informações da compra','terms_text':'Informações da compra e tratamento de dados',
'checkout_title':'Título da compra','checkout_description':'Descrição da compra','name_label':'Campo: Nome','email_label':'Campo: E-mail','phone_label':'Campo: Celular','quantity_label':'Campo: Quantidade','terms_label':'Texto do aceite','checkout_submit':'Botão de reservar','checkout_notice':'Aviso do prazo de reserva','order_title':'Título da página de pedido','order_total':'Rótulo do total','order_pending':'Mensagem: Aguardando pagamento','order_review':'Mensagem: Em análise','order_paid':'Mensagem: Confirmado','order_cancelled':'Mensagem: Cancelado','order_refunded':'Mensagem: Reembolsado','order_expired':'Mensagem: Reserva expirada','pix_copy':'Botão de copiar Pix','receipt_label':'Campo: Comprovante','receipt_button':'Botão de enviar comprovante','order_ticket':'Botão de baixar ingresso','order_link_notice':'Aviso do link privado','order_voucher_notice':'Aviso sobre ingresso oficial'
}
